import type { NextPage } from 'next';
import Head from 'next/head';

import FadeWords from '../components/Fadewords';
import { occupations } from '../constants/siteInfo';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hendra Sadewa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section
          id="intro"
          className="min-h-screen w-full flex flex-col justify-center items-center"
        >
          <h1 className="text-8xl mb-2">Hendra Sadewa</h1>
          <FadeWords words={occupations} className="text-4xl" />
        </section>
      </main>
    </div>
  );
};

export default Home;
