import type { NextPage } from 'next';
import Head from 'next/head';

import FadeWords from '../components/Fadewords';
import { occupations } from '../constants/siteInfo';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Hendra Sadewa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="hero min-h-screen bg-base-200">
          <div className="hero-content text-center">
            <div className="max-w-screen-lg">
              <h1 className="sm:text-2xl md:text-4xl lg:text-8xl mb-2">
                Hendra Sadewa
              </h1>
              <FadeWords
                words={occupations}
                className="sm:text-xl md:text-2xl lg:text-4xl"
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
